steps:
  # Build the container image from project root
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/talking-drum-api'
      - '-f'
      - 'backend/Dockerfile'
      - '.'  # Build context is project root
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/talking-drum-api'
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talking-drum-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/talking-drum-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/talking-drum-api'

timeout: '1200s'
options:
  machineType: 'E2_HIGHCPU_8'
