# Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: talking-drum-api
  annotations:
    # Specify minimum instances to reduce cold starts
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        # Configure container resources
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/timeout: "300s"
        # Allow up to 1000 concurrent requests per container
        run.googleapis.com/max-instances: "10"
        run.googleapis.com/min-instances: "0"
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/talking-drum-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"  
            cpu: "1000m"
        # Health check configuration
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
  traffic:
  - percent: 100
    latestRevision: true
